include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    todo: ignore
    invalid_assignment: warning
    missing_return: warning
    dead_code: info
  exclude:
    - lib/*/*.g.dart

linter:
  rules:
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
    #extra
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - prefer_void_to_null
    - unnecessary_statements
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_returning_null
    - avoid_returning_this
    - avoid_unnecessary_containers
    - await_only_futures
    - camel_case_extensions
    #    - cascade_invocations
    - file_names
    #    - prefer_expression_function_bodies

